### ISSUE TITLE
Add UI login and logout

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs-web#27]
Login (and logout) buttons should be added to the header as per #26.

Before implementing the UI, mockups should be created demonstrating the UI changes and login / logout flow.

Please post mockups as a comment here for feedback. Once a design is decided, implementation can begin.

Note: This issue is only for the UI changes.

**Comment by wzq97** [comment]
![yacs_5](https://user-images.githubusercontent.com/35742213/36068788-a97dd4ba-0eab-11e8-996a-e14173bf8e78.jpg)

**Comment by Bad-Science** [comment]
Thank you @wzq97 :)

So as we discussed, I like the button styles, but we need to have some contrast around the search bar. Could we try something similar but keeping some sort of header backgound?

**Comment by wzq97** [comment]
![yacs_6](https://user-images.githubusercontent.com/35742213/36134788-15991f60-1055-11e8-9b6a-ec7d1f9081f1.jpg)
![yacs_7](https://user-images.githubusercontent.com/35742213/36134789-15a5d6a6-1055-11e8-981c-1ce253722003.jpg)
![yacs_9](https://user-images.githubusercontent.com/35742213/36134791-15b95190-1055-11e8-8557-4e9dc3845085.jpg)
![yacs_8](https://user-images.githubusercontent.com/35742213/36134790-15afaa14-1055-11e8-9419-64ac5b6a2c6a.jpg)

I added some shadow under the header so it looks separated from the background.  Not so sure about the search bar... I think the last one looks the best? :\

**Comment by Bad-Science** [comment]
This is done as of #69
