### ISSUE TITLE
Display location of each period

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs-web#29]
https://github.com/YACS-RCOS/yacs/issues/277 Adds location data to the API.

We should display this data in the courses page or in the schedules page for users to see.

If we cannot fit it in the existing courses view, we should put it in the schedule blocks on the schedule page, and add it to the courses view when implementing the next design iteration.

**Comment by marchdan** [comment]
It should fit nicely within the section information bars

**Comment by marchdan** [comment]
Has been added to the schedules page. Just need actual data to parse in.

**Comment by marchdan** [comment]
A PR has been made to display this data on the schedules view. Will begin to look at plans to integrate this into the course view, but integration will need to wait until other UI changes take place

**Comment by Bad-Science** [comment]
resolved as of #42 
Thanks @marchdan !
