### ISSUE TITLE
Move models to their own separate model folder.

### ISSUE THREAD

**Issue by milnej** [YACS-RCOS/yacs-web#32]
Currently the models in the yacs-web/src/app folder are not well organized; they are all in their own separate folders. We should create a new model folder where all models will be saved and use the convention:
name.model.ts
This should be placed in the folder:
yacs-web/src/app/models
This would mean that we also need to update all the file locations that use these models.

The current models are:
- course-list/course/course.ts
- course-list/section/period.ts
- course-list/section/section.ts
- schedule-view/schedule/schedule.ts
- schedule-view/schedule-event/schedule-event.ts
- school-list/department/department.ts
- school-list/school/school.ts

**Comment by marchdan** [comment]
Changes have been made. Double checking completion before pushing to fork

**Comment by marchdan** [comment]
Multiple files overlap with a recent RP of mine. Will wait for resolution of said PR before pushing so as to avoid confusion

**Comment by Bad-Science** [comment]
Fixed as of #47 

Thanks again @marchdan !
