### ISSUE TITLE
Incorrect test color on schedule view

### ISSUE THREAD

**Issue by marchdan** [YACS-RCOS/yacs-web#45]
On the Schedule view for a test schedule created, there was a class with a blue background, but red text

**Comment by marchdan** [comment]
![wrong color issue](https://user-images.githubusercontent.com/35609442/37060691-0b60af52-215f-11e8-9175-9da96124ba16.png)

**Comment by marchdan** [comment]
Error seems to only occur with this specific schedule. Have not been able to see error happen with any alternative set up of schedule. Always happen when this schedule is constructed this exact way, even color scheme is different.

**Comment by marchdan** [comment]
Issue has resolved, waiting for a conflicting previous PR to be finished before being able to correctly implement changes

**Comment by marchdan** [comment]
PR submitted, change was made to correct the faulty color array, and to account for more classes than available colors

**Comment by Bad-Science** [comment]
Fixed as of #50 

Thanks @marchdan !
