### ISSUE TITLE
Update the past and current developers on the About page

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs-web#56]
Title says it all! Many of the current developers need to be moved to past, and everyone who is working on YACS this semester needs to be added to the current developers!

**Comment by Bad-Science** [comment]
We should also add the NYU devs. @bradleybrecher - can we get a list of each member's preferred name and github handle? I don't think I have a good list for this. (everyone who would like to be added to the contributors page, that is)

**Comment by bradleybrecher** [comment]
@Bad-Science Here is the list,

Bradley- @bradley.brecher
Alisha- @alishasonawalla
Mahi - @mahi-g
Andres - @@guarner8
Jody - @jodz959
Hao - @hhyy233

**Comment by Bad-Science** [comment]
Thanks @bradleybrecher !

@wzq97

**Comment by Bad-Science** [comment]
Fixed as of #67
